### ISSUE TITLE
Link to absinthe_example in docs leads to 404

### ISSUE THREAD

**Issue by seeekr** [absinthe-graphql/absinthe_tutorial#3]
... should instead probably link to this project?

Couldn't find the source of the docs, would otherwise have sent a PR!

Cheers,
Denis

ps. Sorry, here: "If you’d like to cheat, you can find the finished code for the tutorial in the Absinthe Example project on GitHub." from https://hexdocs.pm/absinthe/start.html#content

**Comment by KritR** [comment]
Should be fixed.

**Comment by seeekr** [comment]
Fix confirmed.
